import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: 'TutoLearn Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <header style={{ backgroundColor: 'lightblue' }}>
          header RootLayout
        </header>
        <main>
        {children}
        </main>
        <footer style={{ backgroundColor: 'lightgreen' }}>
          footer RootLayout
        </footer>
      </body>
    </html>
  );
}
